### ISSUE TITLE
Error Unknown Project

### ISSUE THREAD

**Issue by syntaxer** [Franckyi/CMPDL#12]
I'm getting Error Unknown Project (293960) after I click Next at 
Step 1/4: Choose a modpack
from url: https://www.feed-the-beast.com/projects/ftb-continuum

Modpack: FTB Continuum
It used to work before they released the 1.1.0 beta version of the modpack

I'm using version 2.1.1 of CMPDL

**Comment by HarcoChen** [comment]
That's what happened to me.

**Comment by Ashendale** [comment]
Adding to this: I cannot download using the URL, project ID or zip file (tried 3 different packs - no go).

When I tried using the zip file I got burried in error boxes (consider having a file output only, instead of popups - like the one I got in the end and will post below in a pastebin link, for you to see what happened)

The error output at the end was this:

https://pastebin.com/uJE44n89

**Comment by skyecodes** [comment]
I'm very busy right now, and for the next two weeks.
I'll try to fix that if I have enough time, but right now I can't, sorry.

**Comment by skyecodes** [comment]
It seems that the [CurseMeta API](https://cursemeta.dries007.net/) is broken.
So there's nothing I can do to improve the situation.

**Comment by sxjeru** [comment]
Can not use other CurseForge api?
In my opinion, this is the best Curse Modpack Downloader.

**Comment by skyecodes** [comment]
[I've released a hotfix while the CurseMeta API is broken.](https://github.com/Franckyi/CMPDL/releases/tag/v2.1.1-hotfix)
You must download the modpack ZIP file first, then use the "From ZIP file" mode to download the mods and configuration files.

**Comment by syntaxer** [comment]
Thanks for taking from your time to release this hotfix

**Comment by xela-zone** [comment]
Right now there is a staging server available from curseMeta API: https://staging_cursemeta.dries007.net/

**Comment by skyecodes** [comment]
@mralext20 Yep, I'll try to work on a fix using the new CurseMeta v3 beta version. Though it may break at any moment.

**Comment by anar4732** [comment]
Please fix ASAP

**Comment by sxjeru** [comment]
Now the [curseMeta API](https://staging_cursemeta.dries007.net/) is down, only remains an error.
>Internal Server Error

Maybe the new CurseForge broke it.

**Comment by skyecodes** [comment]
[I pushed a new version (2.3.0) that should hopefully fix the issue.](https://github.com/Franckyi/CMPDL/releases/tag/v2.3.0) Please tell me if you still have this problem with the new version.

**Comment by skyecodes** [comment]
I'm closing the issue. If you still experience this problem, please comment and I'll reopen the issue.
