### ISSUE TITLE
Weird JAR class path issues

### ISSUE THREAD

**Issue by goodtrailer** [Franckyi/CMPDL#18]
I'm on Ubuntu 18/19 and using OpenJDK 8. Running `java -jar cmpdl-2.2.0.jar` returns `Error: Could not find or load main class com.github.franckyi.cmpdl.CMPDL`. Opening the JAR file, the manifest file correctly points to `com.github.franckyi.cmpdl.CMPDL`, and running `java -cp cmpdl-2.2.0.jar com.github.franckyi.cmpdl.CMPDL` still returns the same error. This issue persists in older versions of CMPDL too. Vazkii's CMPDL does not show the same error.

**Comment by skyecodes** [comment]
Strange. Have you installed OpenJFX ? I think there's an openjfx package on Ubuntu.

**Comment by goodtrailer** [comment]
Yes, the specific package names are `openjfx` and `openjdk-8-jdk`, not sure if that helps at all. I checked to see if there were other conflicting JDK versions, but those were the only ones that showed up from the package search.

**Comment by goodtrailer** [comment]
**Solution:**
I figured out the issue, but it's definitely strange. Instead of using OpenJDK and OpenJFX, you must specifically install and run **Oracle JDK 8's** java executable. It seems to be an issue with OpenJFX. Whether I was on Windows 10 or Ubuntu 18/19, using any version other than Oracle JDK 8 threw the class path issue.

JDK versions I tried:
Oracle JDK 11, 12
OpenJDK 10, 11, 12
