### ISSUE TITLE
Support for packs from https://www.curseforge.com/minecraft/modpacks ??

### ISSUE THREAD

**Issue by MuninnAndHuginn** [Franckyi/CMPDL#3]
It seems that most packs are now being published to this new curseforge location https://www.curseforge.com/minecraft/modpacks. I don't see an immediate way to get a zip location from these pages. Someone might have to use the twitch app and cross reference the https requests with the data from the website to figure out what's going on here. 
I don't have windows so no twitch client for me. I was using Vazkii's CMPDL before with great success but since they switched to this whole twitch thing it looks like they are locking users into their app.

**Comment by MuninnAndHuginn** [comment]
Inspection of the page source leaves a project ID like 256183 for instance from the Download/Install Buttons a code snippet like this one from SkyFactory3 inside the data-action-value section of the a tag.

This matches the data inside the ccip file that you get from trying to click "install" along with a project "file" identifier number.

**Comment by skyecodes** [comment]
I think I'm gonna use the [CurseMeta API](https://cursemeta.dries007.net) instead of manually crawling webpages. But it will take some time to update.
