### ISSUE TITLE
Modpack override files are not always copied correctly

### ISSUE THREAD

**Issue by roothorick** [Franckyi/CMPDL#4]
May be Linux-specific.

Example affected pack: Space Astronomy 2 https://minecraft.curseforge.com/projects/space-astronomy-2

Log says that overrides were copied, but they don't show up in the penultimate download folder.

**Comment by skyecodes** [comment]
I reproduced the bug on Linux.
I still don't really know what causes this bug, but I think I'll fix it for 2.1.0-beta.
Again, sorry for the inconvenience.
